#config tomcat port
server:
  port: 8888
#spring.profiles.active=prod

#配置磁盘路径
web: 
  upload-path: G:/Tomcat/webstaticfile/

#config database datasource     
spring:
# HTTP ENCODING
  http:
    encoding.charset: UTF-8
    encoding.force: true  
  datasource:  
    url: 'jdbc:mysql://localhost:3306/mycenter?characterEncoding=utf8&useSSL=false'
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #连接池的配置信息
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
# WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
#是否启用StatFilter默认值true
    druid:
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: false
        session-stat-max-count: 1000
        principal-session-name: admin
        principal-cookie-name: admin
        profile-enable: true
# StatViewServlet配置
#展示Druid的统计信息,StatViewServlet的用途包括：1.提供监控信息展示的html页面2.提供监控信息的JSON API
#是否启用StatViewServlet默认值true
      stat-view-servlet:
        enabled: true
#根据配置中的url-pattern来访问内置监控页面，如果是上面的配置，内置监控页面的首页是/druid/index.html例如：
#http://110.76.43.235:9000/druid/index.html
#http://110.76.43.235:8080/mini-web/druid/index.html
        url-pattern:  /druid/*
#允许清空统计数据
        reset-enable:  true
        login-username:  admin
        login-password:  admin
#StatViewSerlvet展示出来的监控信息比较敏感，是系统运行的内部情况，如果你需要做访问控制，可以配置allow和deny这两个参数
#deny优先于allow，如果在deny列表中，就算在allow列表中，也会被拒绝。如果allow没有配置或者为空，则允许所有访问
#配置的格式
#<IP>
#或者<IP>/<SUB_NET_MASK_size>其中128.242.127.1/24
#24表示，前面24位是子网掩码，比对的时候，前面24位相同就匹配,不支持IPV6。
        allow: 
        deny: 128.242.127.1/24,128.242.128.1
# Spring监控配置，说明请参考Druid Github Wiki，配置_Druid和Spring关联监控配置
#spring.datasource.druid.aop-patterns= # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔

#视图解析
  mvc:
    static-path-pattern: /**
    view:
      prefix: /
      suffix: .jsp
#静态资源文件
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  jpa: 
    database: mysql


#config Mybatis
mybatis:
  mapper-locations: classpath:com/yyt/*/*/sqlmapper/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml
#别名
#mybatis.type-aliases-package:com.example.demo.domain
  
#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    
#自带日志配置
logging:
  config: classpath:log4j2-spring.xml
#logging.level.root=INFO
#logging.level.org.springframework.web=DEBUG
#logging.level.org.hibernate=ERROR
#logging.path=D:\\demo1
#logging.file=d:\\springboot3\\log\\demo2.log